theme: jekyll-theme-cayman
title: Collection of Adam Coviensky's Personal and Coursework
description: This website contains personal work and coursework for my MSc in Data Science from Columbia University
